spring:
  application:
    name: warehouse-service
  data:
    mongodb:
      uri: ${MONGO_URI}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

kafka:
  broker: ${KAFKA_BROKER}
  apiKey: ${CONFLUENT_API_KEY}
  apiSecret: ${CONFLUENT_API_SECRET}

jwt:
  secret: ${JWT_SECRET}
  expirationMillis: ${JWT_EXPIRATION:3600000}

server:
  port: ${SERVER_PORT:8094}
