version: "3.9"

services:
  # ==== SPRING BOOT SERVICES ====
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    volumes:
      - ./config/kafka-config.yml:/app/config/kafka-config.yml
      - ./config/redis-config.yml:/app/config/redis-config.yml
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/config/
      SPRING_PROFILES_ACTIVE: docker
      APP_NAME: auth-service
      MONGO_URI: ${MONGO_URI}
      KAFKA_BROKER: ${KAFKA_BROKER}
      CONFLUENT_API_KEY: ${CONFLUENT_API_KEY}
      CONFLUENT_API_SECRET: ${CONFLUENT_API_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "8001:8080"
    networks:
      - backend

  consolidation-service:
    build: ./services/consolidation-service
    container_name: consolidation-service
    volumes:
      - ./config/kafka-config.yml:/app/config/kafka-config.yml
      - ./config/redis-config.yml:/app/config/redis-config.yml
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/config/
      SPRING_PROFILES_ACTIVE: docker
      APP_NAME: consolidation-service
      MONGO_URI: ${MONGO_URI}
      KAFKA_BROKER: ${KAFKA_BROKER}
      CONFLUENT_API_KEY: ${CONFLUENT_API_KEY}
      CONFLUENT_API_SECRET: ${CONFLUENT_API_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "8003:8080"
    networks:
      - backend

  parcel-service:
    build: ./services/parcel-service
    container_name: parcel-service
    volumes:
      - ./config/kafka-config.yml:/app/config/kafka-config.yml
      - ./config/redis-config.yml:/app/config/redis-config.yml
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/config/
      SPRING_PROFILES_ACTIVE: docker
      APP_NAME: parcel-service
      MONGO_URI: ${MONGO_URI}
      KAFKA_BROKER: ${KAFKA_BROKER}
      CONFLUENT_API_KEY: ${CONFLUENT_API_KEY}
      CONFLUENT_API_SECRET: ${CONFLUENT_API_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "8005:8080"
    networks:
      - backend

  pricing-service:
    build: ./services/pricing-service
    container_name: pricing-service
    volumes:
      - ./config/kafka-config.yml:/app/config/kafka-config.yml
      - ./config/redis-config.yml:/app/config/redis-config.yml
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/config/
      SPRING_PROFILES_ACTIVE: docker
      APP_NAME: pricing-service
      MONGO_URI: ${MONGO_URI}
      KAFKA_BROKER: ${KAFKA_BROKER}
      CONFLUENT_API_KEY: ${CONFLUENT_API_KEY}
      CONFLUENT_API_SECRET: ${CONFLUENT_API_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "8006:8080"
    networks:
      - backend

  route-optimization-service:
    build: ./services/route-optimization-service
    container_name: route-optimization-service
    volumes:
      - ./config/kafka-config.yml:/app/config/kafka-config.yml
      - ./config/redis-config.yml:/app/config/redis-config.yml
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/config/
      SPRING_PROFILES_ACTIVE: docker
      APP_NAME: route-optimization-service
      MONGO_URI: ${MONGO_URI}
      KAFKA_BROKER: ${KAFKA_BROKER}
      CONFLUENT_API_KEY: ${CONFLUENT_API_KEY}
      CONFLUENT_API_SECRET: ${CONFLUENT_API_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "8007:8080"
    networks:
      - backend

  tracking-service:
    build: ./services/tracking-service
    container_name: tracking-service
    volumes:
      - ./config/kafka-config.yml:/app/config/kafka-config.yml
      - ./config/redis-config.yml:/app/config/redis-config.yml
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/config/
      SPRING_PROFILES_ACTIVE: docker
      APP_NAME: tracking-service
      MONGO_URI: ${MONGO_URI}
      KAFKA_BROKER: ${KAFKA_BROKER}
      CONFLUENT_API_KEY: ${CONFLUENT_API_KEY}
      CONFLUENT_API_SECRET: ${CONFLUENT_API_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "8008:8080"
    networks:
      - backend

  # ==== PYTHON SERVICES ====
  chatbot-service:
    build: ./services/chatbot-service
    container_name: chatbot-service
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      KAFKA_BROKER: ${KAFKA_BROKER}
      CONFLUENT_API_KEY: ${CONFLUENT_API_KEY}
      CONFLUENT_API_SECRET: ${CONFLUENT_API_SECRET}
      MONGO_URI: ${MONGO_URI}
    ports:
      - "8002:8080"
    networks:
      - backend

#  eta-service:
#    build: ./services/eta-service
#    container_name: eta-service
#    environment:
#      REDIS_HOST: ${REDIS_HOST}
#      REDIS_PORT: ${REDIS_PORT}
#      REDIS_PASSWORD: ${REDIS_PASSWORD}
#      KAFKA_BROKER: ${KAFKA_BROKER}
#      CONFLUENT_API_KEY: ${CONFLUENT_API_KEY}
#      CONFLUENT_API_SECRET: ${CONFLUENT_API_SECRET}
#      MONGO_URI: ${MONGO_URI}
#    ports:
#      - "8004:8080"
#    networks:
#      - backend

  warehouse-service:
    build: ./services/warehouse-service
    container_name: warehouse-service
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      KAFKA_BROKER: ${KAFKA_BROKER}
      CONFLUENT_API_KEY: ${CONFLUENT_API_KEY}
      CONFLUENT_API_SECRET: ${CONFLUENT_API_SECRET}
      MONGO_URI: ${MONGO_URI}
    ports:
      - "8009:8080"
    networks:
      - backend

  # ==== API GATEWAY ====
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    volumes:
      - ./config/kafka-config.yml:/app/config/kafka-config.yml
      - ./config/redis-config.yml:/app/config/redis-config.yml
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/config/
      SPRING_PROFILES_ACTIVE: docker
      APP_NAME: api-gateway
      AUTH_SERVICE_URL: http://auth-service:8080
      CHATBOT_SERVICE_URL: http://chatbot-service:8080
      CONSOLIDATION_SERVICE_URL: http://consolidation-service:8080
      ETA_SERVICE_URL: http://eta-service:8080
      PARCEL_SERVICE_URL: http://parcel-service:8080
      PRICING_SERVICE_URL: http://pricing-service:8080
      ROUTE_OPTIMIZATION_SERVICE_URL: http://route-optimization-service:8080
      TRACKING_SERVICE_URL: http://tracking-service:8080
      MONGO_URI: ${MONGO_URI}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      KAFKA_BROKER: ${KAFKA_BROKER}
      CONFLUENT_API_KEY: ${CONFLUENT_API_KEY}
      CONFLUENT_API_SECRET: ${CONFLUENT_API_SECRET}
    ports:
      - "8000:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
